#ifndef VARIAVEIS_GLOBAIS_HPP_INCLUDED
#define VARIAVEIS_GLOBAIS_HPP_INCLUDED

const int LARGURA_T = 1024;
const int ALTURA_T = 768;
const int FPS = 60;
const int NUM_BALAS = 5;
const int NUM_INIMIGOS = 10;
const int NUM_ITENS = 10;
const int NUM_ESTRELAS = 100;
const int NUM_PLANOS = 3;

enum TECLAS {CIMA, BAIXO, ESQUERDA, DIREITA, ESPACO, ENTER};
enum IDS {JOGADOR, PROJETIL, INIMIGOS, ESTRELA};

#endif // VARIAVEIS_GLOBAIS_HPP_INCLUDED
